trigger: 
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: tfvalidate
    jobs:
      - job: validate
        continueOnError: false
        steps:
          - task: TerraformInstaller@1
            displayName: tfinstall
            inputs:
              terraformVersion: '1.4.6'
          - task: TerraformTaskV4@4
            displayName: init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Azure subscription 1(1)(c4d004c5-5fd9-4d27-821f-5fcceea4e956)'
              backendAzureRmResourceGroupName: 'terraform_ansible'
              backendAzureRmStorageAccountName: 'terraformansiblerg'
              backendAzureRmContainerName: 'terraformansiblecont'
              backendAzureRmKey: 'terraform.tfstate'
          - task: TerraformTaskV4@4
            displayName: validate
            inputs:
              provider: 'azurerm'
              command: 'validate'
  - stage: tfdeploy
    condition: succeeded('tfvalidate')
    dependsOn: tfvalidate
    jobs: 
      - job: apply
        steps:
          - task: TerraformInstaller@1
            displayName: tfinstall
            inputs:
              terraformVersion: '1.4.6'
          - task: TerraformTaskV4@4
            displayName: init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Azure subscription 1(1)(c4d004c5-5fd9-4d27-821f-5fcceea4e956)'
              backendAzureRmResourceGroupName: 'terraform_ansible'
              backendAzureRmStorageAccountName: 'terraformansiblerg'
              backendAzureRmContainerName: 'terraformansiblecont'
              backendAzureRmKey: 'terraform.tfstate'
          - task: TerraformTaskV4@4
            displayName: plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'Azure subscription 1(1)(c4d004c5-5fd9-4d27-821f-5fcceea4e956)'
          - task: TerraformTaskV4@4
            displayName: apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'Azure subscription 1(1)(c4d004c5-5fd9-4d27-821f-5fcceea4e956)'
